export const SPORT_TYPES = [
  "Badminton",
  "Baseball",
  "Basketball",
  "Bowling",
  "Boxing",
  "Climbing",
  "Cricket",
  "Cycling",
  "Dance",
  "Dodgeball",
  "Football",
  "Frisbee",
  "Golf",
  "Gymnastics",
  "Handball",
  "Hiking",
  "Hockey",
  "Kickball",
  "Lacrosse",
  "Martial Arts",
  "Pickleball",
  "Racquetball",
  "Rock Climbing",
  "Rowing",
  "Rugby",
  "Running",
  "Skating",
  "Skateboarding",
  "Soccer",
  "Softball",
  "Squash",
  "Surfing",
  "Swimming",
  "Table Tennis",
  "Tennis",
  "Track & Field",
  "Ultimate Frisbee",
  "Volleyball",
  "Water Polo",
  "Weightlifting",
  "Wrestling",
  "Yoga"
] as const

export type SportType = (typeof SPORT_TYPES)[number]
